http: more flexible exceptional responses
scylladb/seastar pull request #1569
Opened 2023-03-23 08:46 UTC by jcsp

It is convenient for HTTP request handlers to be able to throw an exceptions with arbitrary responses:
- for general exceptions, setting the response content type and providing the full body.
- for redirects, specify what kind of redirect status should be used

An example of needing to set content type + body in Redpanda is where we have a configuration PUT handler that validates the request, and on invalid input returns a 400 status with a JSON body containing a dict of config key to the validation error.  This wasn't possible when the HTTP exception classes would always assume the content of a `httpd::base_exception` was a plain string, and wrap it in a generic exception JSON doc.

An example of setting a custom status on a redirect is where we redirect certain HTTP requests to raft leader nodes, where the default `moved_permanently` status doesn't make sense, and we use `temporary_redirect` instead.

2023-03-23 12:44 UTC, nyh requested changes
You changes look good to me, I have some minor requests in my review, but I also want to make a comment on the bigger picture and raise the possiblity that maybe (?) these changes aren't needed:

In the Scylla project, when we implemented the HTTP-based DynamoDB API we apparently encountered the same problems that you did - we needed to have better control over the error responses, which needed to have a specific structure that DynamoDB defines (they aren't meant to be a string consumed by humans), specific error codes, and specific content type. What we ended up doing (see alternator/server.cc in the Scylla project) was to subclass `handler_base`, calling the subclass "api_handler". The handler function of this api_handler calls the real handling function, but catches exceptions from it. Then exceptions of specific types are converted to error messages by building an actual response - an http error code, a body, and content-type, NOT propagating the exceptions further down the the server.

This approach gave our server full control of how different exceptions are formatted in the response, and we didn't need to modify the server code as you did.

I agree that if there is a way that the server can be modified (as you did) to save other people the need to to do this subclassing, it's a good thing. But I'm not yet convinced that you really saved developer work... I think in most cases you would want (as we did in Scylla) some sort of centralized layer that translates exceptions from deep in the code into user-visible error HTTP error responses, and this layer can be a handler_base subclass. So, if you have such a subclass anyway, do you really need the new features?

2023-04-11 10:39 UTC, jcsp commented
@nyh thanks for your feedback: I had a busy couple of weeks but hoping to find time to take a closer look at this again soon.  We do have some wrappers for our HTTP handlers, so maybe it makes sense to do it there.

Does Scylla use `http::base_exception` at all?  If not maybe we should remove it: it feels a bit inconsistent to have an exception type that can generate http responses, but only in a limited way.  Maybe this is a place where we should go all the way one way or the other: either flesh out the exception class to enable passing arbitrary responses, or get rid of it and establish a convention that users of the service interface should implement their own exception catching?

2023-04-19 12:03 UTC, nyh commented
> Does Scylla use `http::base_exception` at all? If not maybe we should remove it: it feels a bit inconsistent to have an exception type that can generate http responses, but only in a limited way.

I agree. Scylla uses http::base_exception directly in only one place, in the REST API server - it is used to generate an error with error code reply::status_type::internal_server_error and the string "API call is not supported yet". But it also uses various exceptions from `<seastar/http/exception.hh>` like `http::bad_param_exception`, all of which inherit from `base_exception`.

I'm not a big fan of this API, and like I said earlier when I wrote a second HTTP server handler in ScyllaDB (Alternator - the DynamoDB API server), I didn't use it. I think that in general many HTTP servers need to have full control over error responses (just like over successful responses), and need an application-specific way to convert exceptions to the error responses - and have no use for canned exceptions.

Maybe @amnonh who originally designed this API can comment about the reason why it looks the way that it does.

2023-12-08 18:59 UTC, dotnwat commented
@nyh @amnonh I think you can close this PR please? I'm going to handle upstreaming these changes for John. I've split out the redirect bits into https://github.com/scylladb/seastar/pull/1995 with feedback applied, and will handle separately the generic exception handling which had more feedback.

2023-12-10 18:11 UTC, closed without merging