core/on_internal_error: always log error with backtrace
scylladb/seastar pull request #1584
Opened 2023-03-29 10:59 UTC by denesb

For some reason the backtrace was only logged when `abort_on_internal_error` was set to true, otherwise the backtrace was only attached to the exception thrown but not the log message. This doesn't makes sense and it means that if the exception is not printed (correctly) the backtrace is lost completely. This patch fixes this and makes sure the error message is logged with a backtrace, regardless of what `abort_on_internal_error` is set to. No performance degradation is expected from this, internal error should be *very* rare and once they happen, the performance of the affected code path is not interesting anymore.

2023-03-29 11:54 UTC, nyh requested changes
Thanks, but please also change the wording of the comment in include/seastar/core/on_internal_error.hh. The comment on both `on_internal_error` instances (note there are two versions, with similar comments!) says it will "either log and abort or throw".

By the way, maybe you also need to fix the two overloads of on_internal_error, not just the one you fixed?

2023-03-29 12:01 UTC, denesb commented
New in v2:
* Fix the other overload too.
* Update comments of both overloads.

2023-03-29 12:06 UTC, nyh approved these changes

2023-03-29 12:22 UTC, closed without merging

2023-05-05 12:22 UTC, bhalevy commented
Need to backport this fix to all live versions please.
I guess we need to open an issue for it.

2023-05-05 12:27 UTC, bhalevy commented
Opened https://github.com/scylladb/seastar/issues/1648