future: deprecate future::get0()
scylladb/seastar pull request #2059
Opened 2024-01-28 14:01 UTC by avikivity

In the days when futures carried tuples, it was useful to get the first/only element. But it's now a synonym for get(), so deprecate it.

2024-01-28 14:34 UTC, nyh requested changes
I'm in favor of this deprecation, but I wonder if it wouldn't cause unnecessary headaches to Seastar projects which will now need to change all the calls to get0() or face hundreds of warning messages.
Could we make "get0()" an exact synonym of get()" - with less code (no separate return type, etc.) and then we won't mind just leaving it there for years?

The reason I'm asking for "Request changes" is that I think you forgot to through Seastar itself and replace all calls to get0() by get() - we have many of those in various helper classes, in example applications, and so on. Didn't you get a lot of deprecation warnings when building Seastar with this patch?

2024-01-28 14:35 UTC, nyh commented
> Didn't you get a lot of deprecation warnings when building Seastar with this patch?

I see in the CI that you did :-)

2024-02-13 05:50 UTC, tchaikov commented
@avikivity now that #2069 has been merged, could you rebase this change? i think it's should be ready now. i tested it locally. the tree built just fine after applying this change.

2024-04-15 06:13 UTC, tchaikov commented
> @avikivity now that #2069 has been merged, could you rebase this change? i think it's should be ready now. i tested it locally. the tree built just fine after applying this change.

i took the liberty to rebase this change at #2188

2024-04-25 05:34 UTC, tchaikov commented
closing, since #2188 has been merged.

2024-04-25 05:34 UTC, closed without merging