metrics: Internalize metric label sets
scylladb/seastar pull request #2561
Opened 2024-11-28 15:21 UTC by StephanDollberg

The major memory user in the metric subsystem is the per series label
sets.

This is for two reasons:
 - The labels are stored multiple times in different places: Twice as
   part of `registered_metric` (one current labels and one original one
   for relabeling - these are often just the same), one copy as the
   lookup key in the values map and another final copy in the metadata
   copy for scraping
 - Lots of the labels are actually duplicated across metric series. For
   example for one io-queue class/mountpoint/iogroup combination you get
   15 series all with the same labels. Similar is true for other metrics
   like reactor or scheduler metrics. In Redpanda we have an even more
   extreme pattern where per partition metrics create more than 60
   series with the same label set.

One idea to improve this would be to intern the individual label
strings. In theory this would give improvements on top of the
duplication described above. Most label keys and values are duplicated
even if not all labels are the same (e.g.: shard).

On a more detailed look this however wouldn't be very effective. Most
labels are fairly short, e.g. looking at some seastar and redpanda
metrics:

```
io_queue...{class="raft",iogroup="0",mountpoint="none",shard="0"}
redpanda...{namespace="kafka",partition="9985",shard="2",topic="foobar"}
```

Each of the label key and values are shorter than 16 bytes and hence fit
into the seastar short string optimization. Hence, each string only
takes 16 bytes. In the above example maybe one of the eight strings
might leave the SSO length (e.g.: mountpoint and topic) but those are in
the minority.

Interning the string in less than 16 bytes is not trivial so the gain
would actually not be that large (deletion needs to be thread safe as
the metadata might be copied to different shards at scrape time).

There is further hidden overhead. Labels are stored in a `std::map` for
fast lookup. Each node in the map has a ~32 byte overhead for the node
struct. So even at a zero overhead internalisation we could only save
about 2x in the most likely case.

Hence this patch takes the strategy of internalizing the whole labels
set (`std::map`). This means that we also internalize map overhead and
still get an overall reduction as described above. For the actual
internalization we store the labels `std::map` in a `std::shared_ptr`
(for cross shared safety). It's stored in a `std::set` for lookup when
adding new metrics.

In Redpanda this patch reduces the metrics memory usage by a
factor of 3-4 and hence saving gigabytes of memory at high partition
counts (yes we likey have too many metrics).

This also makes `update_metrics_if_needed` faster as less copying is
needed and also increases cache locality at scrape time making that cheaper
as well (a yet to be committed microbench by Travis Downs shows a ~10%
improvement).

Once all other shared_ptr references have gone out of scope we need to
delete the entry out of the internalization set. We do this scan in
`update_metrics_if_needed`. The overhead is minimal as the set doesn't
actually get super big and extra overhead is compensated by
`update_metrics_if_needed` being cheaper as mentioned above. Ideally we
could do some deleter tricks but this is being complicated by thread
safety issues in case the last reference is not on the origin shard.

2024-12-05 08:09 UTC, amnonh commented
I'm reviewing the code; so far, I just wanted some clarification. My concern is about what happens during metrics reporting when you can get preemptions. Maybe that's not an issue

2024-12-05 08:56 UTC, StephanDollberg commented
> I'm reviewing the code; so far, I just wanted some clarification. My concern is about what happens during metrics reporting when you can get preemptions. Maybe that's not an issue

Yeah that shouldn't be an issue (obviously let me know if you see one). The shared_ptr should avoid any thread safety issues and the SP type is const explicitly to avoid accidental modification once internalised.

2024-12-07 09:26 UTC, amnonh requested changes
Overall, it looks good and takes a good approach. My comments are around code documentation; that would help to make it clearer.

I agree that, theoretically, we could have dropped the GC and based the deletion on the pointer self-counter, but it's not worth the extra complexity. We don't expect that metrics changing and deletion will happen a lot.

2024-12-09 09:53 UTC, StephanDollberg commented on include/seastar/core/metrics_api.hh
> +using metric_instances = std::map<internalized_holder, register_ref, std::less<>>;
It's needed yes. It enables heterogenuous lookupand hence we can use the extra operator< overloads defined for `internalized_holder`.

2024-12-09 09:53 UTC, StephanDollberg commented on include/seastar/core/metrics_api.hh
> +    const register_ref& at(const internalized_labels_ref& l) const {
Yes just using `labels_type` would be better here. The problem is that `std::map::at` only supports heterogenuous lookup as part of C++26 [1][2].

As a workaround we could just do it manually and do a `find` first and if not found throw a `std::out_of_range` exception ourselves?

[1] https://stackoverflow.com/a/75329629/893693
[2] https://en.cppreference.com/w/cpp/container/map/at

2024-12-09 10:07 UTC, amnonh commented on include/seastar/core/metrics_api.hh
> +    const register_ref& at(const internalized_labels_ref& l) const {
What makes it more confusing is that you create an object implicitly by passing a const reference to a method that gets an object

2024-12-09 14:49 UTC, StephanDollberg commented on include/seastar/core/metrics_api.hh
> +    const register_ref& at(const internalized_labels_ref& l) const {
Yes but this isn't really that different to what happens when you do:

```
std::map<std::string, int> m;
m.at("hello are you there");
```
That will also create and allocate a temporary `std::string` that is only used during lookup.

As suggested above we can work around it though by simply implementing `at` ourselves.

2024-12-09 15:35 UTC, avikivity commented
@amnonh can you measure the improvement for ScyllaDB?

2024-12-09 15:37 UTC, avikivity commented on include/seastar/core/metrics_api.hh
> +
BEGIN FROWN

2024-12-09 15:40 UTC, avikivity commented on include/seastar/core/metrics_api.hh
>      }
Does this change the public API?

2024-12-09 15:44 UTC, avikivity commented
Some comments:
 - I wasn't able to tell if interning would favor one shard over the others; if so we'd want to distribute interning across all shards to avoid skewing memory use.
 - How is the shard label ignored? Maybe it's added later so there's no need to do anything
 - I'd much prefer a foreign_ptr approach (especially if we hash-distribute interning)
 - A vector of pairs would offer even more compression, as long as the API is still std::map

2024-12-09 19:40 UTC, StephanDollberg commented
> I wasn't able to tell if interning would favor one shard over the others; if so we'd want to distribute interning across all shards to avoid skewing memory use.

> How is the shard label ignored? Maybe it's added later so there's no need to do anything

> I'd much prefer a foreign_ptr approach (especially if we hash-distribute interning)

Let me answer those three together. I probably spoke too much about threadsafety in the commit message and hence caused some confusion.

So in the current patch we don't actually do any cross-shard interning at this point. Hence the shard label gets interned as any other label (it gets added to the label set pretty early). 

The thread safety bit I was talking about comes from the metadata handling which gets copied across shards at scrape time. This is how an internalized label can live on two different shards temporarily. This is where we are already using SPs.

Using a foreign_ptr would be feasible but would make the API/types quite a bit more complicated.

Interning across shards is certainly another step that could be taken. Note that after this change the memory usage taken by the label set (per shard) as part of the overall metrics memory usage goes down 20-30% so it's not like further improving that bit has a massive effect. It would also require a change to the public API I think as that is currently not async. 

Further while it would probably help for reactor etc. metrics for user metrics it's likely that high cardinality series are probably different across shards in other labels than the shard. E.g.: in redpanda for the high cardinality series the partition would be different across shards so you wouldn't get any advantage there.

So it's not immediately clear the added complexity would be worth it.

> A vector of pairs would offer even more compression, as long as the API is still std::map

Yes this would be another memory optimization that could applied. Would need to see how it affects query time though. As mentioned above the improvements aren't massive at that point so this would need to be considered as scrapping is also quite expensive.

2024-12-10 13:04 UTC, avikivity commented on include/seastar/core/metrics_api.hh
>      }
Ok.

2024-12-10 13:11 UTC, avikivity commented
> > I wasn't able to tell if interning would favor one shard over the others; if so we'd want to distribute interning across all shards to avoid skewing memory use.
> 
> > How is the shard label ignored? Maybe it's added later so there's no need to do anything
> 
> > I'd much prefer a foreign_ptr approach (especially if we hash-distribute interning)
> 
> Let me answer those three together. I probably spoke too much about threadsafety in the commit message and hence caused some confusion.
> 
> So in the current patch we don't actually do any cross-shard interning at this point. Hence the shard label gets interned as any other label (it gets added to the label set pretty early).
> 
> The thread safety bit I was talking about comes from the metadata handling which gets copied across shards at scrape time. This is how an internalized label can live on two different shards temporarily. This is where we are already using SPs.

I don't see std::shared_ptr in the metrics code now.

> 
> Using a foreign_ptr would be feasible but would make the API/types quite a bit more complicated.
> 


Could we, perhaps, capture the local owner of all the metrics and pass it around as a foreign_ptr? It would have to be immutable for that to work.

> Interning across shards is certainly another step that could be taken. Note that after this change the memory usage taken by the label set (per shard) as part of the overall metrics memory usage goes down 20-30% so it's not like further improving that bit has a massive effect. It would also require a change to the public API I think as that is currently not async.

We could (with non-negligible effort) have a fiber to intern after the fact.


> 
> Further while it would probably help for reactor etc. metrics for user metrics it's likely that high cardinality series are probably different across shards in other labels than the shard. E.g.: in redpanda for the high cardinality series the partition would be different across shards so you wouldn't get any advantage there.
> 
> So it's not immediately clear the added complexity would be worth it.
> 
> > A vector of pairs would offer even more compression, as long as the API is still std::map
> 
> Yes this would be another memory optimization that could applied. Would need to see how it affects query time though. As mentioned above the improvements aren't massive at that point so this would need to be considered as scrapping is also quite expensive.

I think it would improve scrape time too. We could add a private interface between metrics and prometheus that exposes the labels as a span. Operating on cold node-based data structures is slow.

Meanwhile, please see if you can drop the dependency on std::shared_ptr. I don't have a suggestion but I do want to prevent its encroachment.

2024-12-11 11:58 UTC, StephanDollberg commented
> I don't see std::shared_ptr in the metrics code now.

> Meanwhile, please see if you can drop the dependency on std::shared_ptr. I don't have a suggestion but I do want to prevent its encroachment.

Yes you are totally right of course. I always forget about the seastar version when I see an unqualified `shared_ptr`. I do see now that we already use a `foreign_ptr` in the metadata cross-shard flow. 

So in that case we can actually just replace the `std::shared_ptr` usage with `ss::lw_shared_ptr` (which is also a bit slimmer). All the uses are encompased by the object that is already being sent back via the foreign_ptr so all their destructors will run on the correct shard.

There is the risk of someone just copying out one of the `lw_shared_ptr`s but IMO this is well covered by the shared_ptr non-owner debug checks. E.g.: the `Seastar.unit.prometheus_http` catches this when intentionally introducing a bug here.

In any case I have added two further commits. The first just tightens up the API which makes these accidental copies a bit harder and more explicit (in fact this found an unneeded copy in the protobuf prom impl).

The second commit goes the full way and makes the cross-shard metadata code use individual foreign_ptrs. As suggested above this complicates the API quite a bit and is also more expensive in case the foreign references are the last copies. 

I'd be happy to drop the both of these commits or just the latter. Let me know what you think.

2024-12-11 12:20 UTC, avikivity commented on include/seastar/core/metrics_api.hh
> +#include "seastar/core/shared_ptr.hh"
Please use <> includes, not "" includes.

2024-12-11 12:24 UTC, avikivity commented on include/seastar/core/metrics_api.hh
> +    return lhs.labels() < rhs.labels();
These can be replaces with a transparent comparator (https://en.cppreference.com/w/cpp/container/map/find variants 3, 4) for the key.

But why use an ordered map in the first place?

2024-12-11 12:31 UTC, avikivity commented on include/seastar/core/metrics_api.hh
> +using internalized_set = std::set<internalized_holder, std::less<>>;
This would be a candidate for unordered_set. But since you need ordered compares for the other container, we might as well keep this as is.

2024-12-11 12:34 UTC, avikivity commented on src/core/scollectd.cc
> +#include "seastar/core/shared_ptr.hh"
\<> includes

2024-12-11 12:39 UTC, avikivity commented on include/seastar/core/metrics_api.hh
> +using foreign_metric_id = metric_id_t<foreign_ptr<internalized_labels_ref>>;
I don't understand why we'd want a foreign metric_id. Isn't it too low-level? On remote shards we work with large collections of metrics, not individual metrics ids.

2024-12-11 12:46 UTC, avikivity commented
Regarding cross-shard safety, I think the best approach is to make shard data immutable and have metrics registration clone the data structure, install the metric, and replace the root pointer.

Caveat 1: I don't have a clear mental picture of how it currently works so it may be unnecessary/wrong
Caveat 2: cloning doesn't work during unregistration since it happens in a destructor, perhaps we can set an "invalid" flag and let the next non-noexcept call clean it up

2024-12-11 15:17 UTC, StephanDollberg commented
> Regarding cross-shard safety, I think the best approach is to make shard data immutable and have metrics registration clone the data structure, install the metric, and replace the root pointer.

Sorry I don't fully understand this. So internalized labels are immutable. There is no risk of anybody modifying them.

The "risk" I described in my previous message is someone (accidentally) copying the `lw_shared_ptr` out of the shared metadata structure when processing the metrics for scrape. This doesn't happen today. They are all part of a bigger structure which is already using foreign_ptr (`values_reference`) so effectively everything gets destroyed on the right shard.

I see three ways to address this potential risk:
 - Do nothing: This is debug-checked pretty well via the shared-ptr non-owner checks. 
 - Narrow down the API so that it's harder for someone to do that. From your other comment it sounds like you'd rather not do that. Though if we were to use different datastructures in the shared metadata then this might become a bit cleaner. We could remove the `copy` methods from `metric_info` and `metric_id` and have a completely separate uncopyable `foreign_metric` datastructure.
 - Put each individual labelset lw_shared_ptr into its own foreign_ptr. This would make copying of the shared ptr impossible (other than calling foreign_ptr::copy explicitly)

The current three commits reflect each of those three steps.

2024-12-11 16:31 UTC, avikivity commented on include/seastar/core/metrics_api.hh
> +using foreign_metric_id = metric_id_t<foreign_ptr<internalized_labels_ref>>;
Not even per internalized label set, one foreign_ptr per the entire registered metric set.

2024-12-11 16:39 UTC, avikivity commented
> > Regarding cross-shard safety, I think the best approach is to make shard data immutable and have metrics registration clone the data structure, install the metric, and replace the root pointer.
> 
> Sorry I don't fully understand this. 


First a disclaimer that I'm not well versed in the metrics code so anything I say could be nonsense.

> So internalized labels are immutable. There is no risk of anybody modifying them.

I'm talking about immutablizing the entire metadata structure for all metrics. The idea is that metadata changes very rarely, so we can spend more time when modifying it to fully clone + add, then install the new structure. A foreign_ptr to that immutable structure is safe to traverse across shards.

> 
> The "risk" I described in my previous message is someone (accidentally) copying the `lw_shared_ptr` out of the shared metadata structure when processing the metrics for scrape. This doesn't happen today. They are all part of a bigger structure which is already using foreign_ptr (`values_reference`) so effectively everything gets destroyed on the right shard.

Doesn't values_reference only refer to values, not the metadata?

Maybe I'm wrong and it's already as I'm describing.

> 
> I see three ways to address this potential risk:
> 
> * Do nothing: This is debug-checked pretty well via the shared-ptr non-owner checks.
> * Narrow down the API so that it's harder for someone to do that. From your other comment it sounds like you'd rather not do that. Though if we were to use different datastructures in the shared metadata then this might become a bit cleaner. We could remove the `copy` methods from `metric_info` and `metric_id` and have a completely separate uncopyable `foreign_metric` datastructure.

If we were using Rust then it would make sense to do it. It also makes sense in C++, but in my experience removing copy-ability makes things worse elsewhere.

Since this is a dedicated type (not generic) and its use is heavily tied to cross-shard work, perhaps it does merit this special copy behavior.

We could rationalize this by saying the type has the semantics of unique_ptr (not copyable) and the sharing is an implementation detail and not exposed to its users.


> * Put each individual labelset lw_shared_ptr into its own foreign_ptr. This would make copying of the shared ptr impossible (other than calling foreign_ptr::copy explicitly)

I think this is overkill. foreign_ptr:s aren't free.


> 
> The current three commits reflect each of those three steps.

Thanks for the detailed explanation.

2024-12-11 17:51 UTC, StephanDollberg commented
> I'm talking about immutablizing the entire metadata structure for all metrics. The idea is that metadata changes very rarely, so we can spend more time when modifying it to fully clone + add, then install the new structure. A foreign_ptr to that immutable structure is safe to traverse across shards.

Gotcha, yes that is effectively what happens today (minus it being actually const but that's something we can add). 

> Doesn't values_reference only refer to values, not the metadata?

Yeah it does contain the metadata. The name is a bit confusing I guess :)

Relevant types:

```
using values_reference = shared_ptr<values_copy>;

struct values_copy {
    shared_ptr<metric_metadata> metadata;
    metric_values values;
};
```

> If we were using Rust then it would make sense to do it. It also makes sense in C++, but in my experience removing copy-ability makes things worse elsewhere.

> Since this is a dedicated type (not generic) and its use is heavily tied to cross-shard work, perhaps it does merit this special copy behavior.

> We could rationalize this by saying the type has the semantics of unique_ptr (not copyable) and the sharing is an implementation detail and not exposed to its users.

I didn't really like the whole `copy` stuff neither. Move only seems fine to me from C++ POV in this case. Let me give it a try.

2024-12-11 18:21 UTC, avikivity commented
> > I'm talking about immutablizing the entire metadata structure for all metrics. The idea is that metadata changes very rarely, so we can spend more time when modifying it to fully clone + add, then install the new structure. A foreign_ptr to that immutable structure is safe to traverse across shards.
> 
> Gotcha, yes that is effectively what happens today (minus it being actually const but that's something we can add).
> 
> > Doesn't values_reference only refer to values, not the metadata?
> 
> Yeah it does contain the metadata. The name is a bit confusing I guess :)
> 
> Relevant types:
> 
> ```
> using values_reference = shared_ptr<values_copy>;
> 
> struct values_copy {
>     shared_ptr<metric_metadata> metadata;
>     metric_values values;
> };
> ```
> 

Ah, and we generate it on-demand in update_metrics_if_needed(), rather than during construction.

2024-12-12 01:22 UTC, travisdowns commented
@avikivity - while we have your attention on metrics, what do you estimate the use fraction to be for scollectd vs prometheus for scylladb users? E.g., to help evaluate the effectiveness of changes that improve only the prometheus side.

2024-12-12 07:54 UTC, avikivity commented
> @avikivity - while we have your attention on metrics, what do you estimate the use fraction to be for scollectd vs prometheus for scylladb users? E.g., to help evaluate the effectiveness of changes that improve only the prometheus side.

0:1

2024-12-12 13:34 UTC, StephanDollberg commented
I have pushed a change now that uses a separate datastructure. I think this is a lot cleaner like this.

Unfortunately, we can't strip that much of it for now because of scollectd.

2024-12-12 13:39 UTC, mykaul commented
> I have pushed a change now that uses a separate datastructure. I think this is a lot cleaner like this.
> 
> Unfortunately, we can't strip that much of it for now because of scollectd.

Is anyone still using scollectd?

2024-12-12 17:11 UTC, travisdowns commented
> Is anyone still using scollectd?

I heard from Avi that no, zero people are using scollectd integration in seastar. Seems like a PR to remove support would probably be accepted easily then?

2024-12-17 15:45 UTC, StephanDollberg commented
@mykaul how is that coming along? I have created a PR here to remove it from seastar https://github.com/scylladb/seastar/pull/2586

2024-12-17 16:02 UTC, mykaul commented
> @mykaul how is that coming along? I have created a PR here to remove it from seastar #2586

https://github.com/scylladb/scylladb/pull/17356 - in the process of passing CI.

2024-12-17 16:45 UTC, avikivity commented
I saw build failures compiling scylladb with this series, but all from unit test that reach into the impl namespace.

2024-12-17 16:45 UTC, merged

2024-12-26 08:21 UTC, bhalevy commented
@avikivity / @scylladb/seastar-maint: this change breaks scylla.
I suggest to revert it and probably resubmit while bumping the api level.

Also, again, it's a good example why we should run scylla ci as part of seastar's ci
since scylla is a comprehensive representative of the the library users.

For example:
```
bhalevy@home:~/dev/scylla$ ninja dev-objects
[1/2] ./SCYLLA-VERSION-GEN --output-dir build
[2/5] NINJA build/dev/seastar/libseastar.so
ninja: Entering directory `build/dev/seastar'
ninja: no work to do.
[3/5] CXX build/dev/test/boost/query_processor_test.o
FAILED: build/dev/test/boost/query_processor_test.o 
clang++ -MD -MT build/dev/test/boost/query_processor_test.o -MF build/dev/test/boost/query_processor_test.o.d -std=gnu++23 -I/home/bhalevy/dev/scylla/seastar/include -I/home/bhalevy/dev/scylla/build/dev/seastar/gen/include -Werror=unused-result -fstack-clash-protection -DSEASTAR_API_LEVEL=7 -DSEASTAR_BUILD_SHARED_LIBS -DSEASTAR_SSTRING -DSEASTAR_ENABLE_ALLOC_FAILURE_INJECTION -DSEASTAR_LOGGER_COMPILE_TIME_FMT -DSEASTAR_SCHEDULING_GROUPS_COUNT=16 -DSEASTAR_LOGGER_TYPE_STDOUT -DSEASTAR_TYPE_ERASE_MORE -DFMT_SHARED -I/usr/include/p11-kit-1 -DWITH_GZFILEOP -g -ffile-prefix-map=/home/bhalevy/dev/scylla=. -DSEASTAR_NO_EXCEPTION_HACK -march=westmere -DDEVEL -DSEASTAR_ENABLE_ALLOC_FAILURE_INJECTION -DSCYLLA_ENABLE_ERROR_INJECTION -DSCYLLA_ENABLE_PREEMPTION_SOURCE -O2 -DSCYLLA_BUILD_MODE=dev -Xclang -fexperimental-assignment-tracking=disabled -iquote. -iquote build/dev/gen -std=gnu++23 -g -ffile-prefix-map=/home/bhalevy/dev/scylla=. -DSEASTAR_NO_EXCEPTION_HACK -march=westmere -DBOOST_ALL_DYN_LINK    -fvisibility=hidden -isystem abseil -Wall -Werror -Wextra -Wimplicit-fallthrough -Wno-mismatched-tags -Wno-c++11-narrowing -Wno-overloaded-virtual -Wno-unused-parameter -Wno-unsupported-friend -Wno-missing-field-initializers -Wno-deprecated-copy -Wno-enum-constexpr-conversion -Wno-error=deprecated-declarations -DXXH_PRIVATE_API -DSEASTAR_TESTING_MAIN  -c -o build/dev/test/boost/query_processor_test.o test/boost/query_processor_test.cc
test/boost/query_processor_test.cc:187:35: error: no member named 'id' in 'seastar::metrics::impl::metric_series_metadata'
  187 |         const auto found = metric.id.labels().find("consistency_level");
      |                            ~~~~~~ ^
test/boost/query_processor_test.cc:188:39: error: no member named 'id' in 'seastar::metrics::impl::metric_series_metadata'
  188 |         BOOST_REQUIRE(found != metric.id.labels().cend());
      |                                ~~~~~~ ^
/usr/include/boost/test/tools/old/interface.hpp:85:6: note: expanded from macro 'BOOST_REQUIRE'
   85 |     (P), BOOST_TEST_STRINGIZE( P ), REQUIRE, CHECK_PRED, _ )
      |      ^
/usr/include/boost/test/tools/old/interface.hpp:68:61: note: expanded from macro 'BOOST_TEST_TOOL_IMPL'
   68 |         BOOST_JOIN( BOOST_TEST_TOOL_PASS_PRED, frwd_type )( P, ARGS ),          \
      |                                                             ^
/usr/include/boost/test/tools/old/interface.hpp:51:47: note: expanded from macro 'BOOST_TEST_TOOL_PASS_PRED2'
   51 | #define BOOST_TEST_TOOL_PASS_PRED2( P, ARGS ) P
      |                                               ^
2 errors generated.
[4/5] CXX build/dev/test/boost/group0_test.o
FAILED: build/dev/test/boost/group0_test.o 
clang++ -MD -MT build/dev/test/boost/group0_test.o -MF build/dev/test/boost/group0_test.o.d -std=gnu++23 -I/home/bhalevy/dev/scylla/seastar/include -I/home/bhalevy/dev/scylla/build/dev/seastar/gen/include -Werror=unused-result -fstack-clash-protection -DSEASTAR_API_LEVEL=7 -DSEASTAR_BUILD_SHARED_LIBS -DSEASTAR_SSTRING -DSEASTAR_ENABLE_ALLOC_FAILURE_INJECTION -DSEASTAR_LOGGER_COMPILE_TIME_FMT -DSEASTAR_SCHEDULING_GROUPS_COUNT=16 -DSEASTAR_LOGGER_TYPE_STDOUT -DSEASTAR_TYPE_ERASE_MORE -DFMT_SHARED -I/usr/include/p11-kit-1 -DWITH_GZFILEOP -g -ffile-prefix-map=/home/bhalevy/dev/scylla=. -DSEASTAR_NO_EXCEPTION_HACK -march=westmere -DDEVEL -DSEASTAR_ENABLE_ALLOC_FAILURE_INJECTION -DSCYLLA_ENABLE_ERROR_INJECTION -DSCYLLA_ENABLE_PREEMPTION_SOURCE -O2 -DSCYLLA_BUILD_MODE=dev -Xclang -fexperimental-assignment-tracking=disabled -iquote. -iquote build/dev/gen -std=gnu++23 -g -ffile-prefix-map=/home/bhalevy/dev/scylla=. -DSEASTAR_NO_EXCEPTION_HACK -march=westmere -DBOOST_ALL_DYN_LINK    -fvisibility=hidden -isystem abseil -Wall -Werror -Wextra -Wimplicit-fallthrough -Wno-mismatched-tags -Wno-c++11-narrowing -Wno-overloaded-virtual -Wno-unused-parameter -Wno-unsupported-friend -Wno-missing-field-initializers -Wno-deprecated-copy -Wno-enum-constexpr-conversion -Wno-error=deprecated-declarations -DXXH_PRIVATE_API -DSEASTAR_TESTING_MAIN  -c -o build/dev/test/boost/group0_test.o test/boost/group0_test.cc
test/boost/group0_test.cc:49:62: error: no matching constructor for initialization of 'const internalized_labels_ref &' (aka 'const lw_shared_ptr<const map<basic_sstring<char, unsigned int, 15>, basic_sstring<char, unsigned int, 15>>> &')
   49 |             const auto& registered_metric = metric_family.at({{"shard", "0"}});
      |                                                              ^~~~~~~~~~~~~~~~
/home/bhalevy/dev/scylla/seastar/include/seastar/core/shared_ptr.hh:274:5: note: candidate constructor not viable: cannot convert initializer list argument to 'lw_shared_ptr_counter_base *'
  274 |     lw_shared_ptr(lw_shared_ptr_counter_base* p) noexcept : _p(p) {
      |     ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/bhalevy/dev/scylla/seastar/include/seastar/core/shared_ptr.hh:303:5: note: candidate constructor not viable: cannot convert initializer list argument to 'std::nullptr_t'
  303 |     lw_shared_ptr(std::nullptr_t) noexcept : lw_shared_ptr() {}
      |     ^             ~~~~~~~~~~~~~~
/home/bhalevy/dev/scylla/seastar/include/seastar/core/shared_ptr.hh:304:5: note: candidate constructor not viable: cannot convert initializer list argument to 'const lw_shared_ptr<const map<basic_sstring<char, unsigned int, 15>, basic_sstring<char, unsigned int, 15>>>'
  304 |     lw_shared_ptr(const lw_shared_ptr& x) noexcept : _p(x._p) {
      |     ^             ~~~~~~~~~~~~~~~~~~~~~~
/home/bhalevy/dev/scylla/seastar/include/seastar/core/shared_ptr.hh:314:5: note: candidate constructor not viable: cannot convert initializer list argument to 'lw_shared_ptr<const map<basic_sstring<char, unsigned int, 15>, basic_sstring<char, unsigned int, 15>>>'
  314 |     lw_shared_ptr(lw_shared_ptr&& x) noexcept  : _p(x._p) {
      |     ^             ~~~~~~~~~~~~~~~~~
/home/bhalevy/dev/scylla/seastar/include/seastar/core/shared_ptr.hh:302:5: note: candidate constructor not viable: requires 0 arguments, but 1 was provided
  302 |     lw_shared_ptr() noexcept = default;
      |     ^
/home/bhalevy/dev/scylla/seastar/include/seastar/core/metrics_api.hh:314:59: note: passing argument to parameter 'l' here
  314 |     const register_ref& at(const internalized_labels_ref& l) const {
      |                                                           ^
1 error generated.
ninja: build stopped: subcommand failed.
```

2024-12-26 11:42 UTC, bhalevy commented
```
-            const auto& registered_metric = metric_family.at({{"shard", "0"}});
+            const auto& registered_metric = metric_family.at(make_lw_shared<seastar::metrics::impl::labels_type>({{"shard", "0"}}));
```

This may compile but does it do the right thing?
Wouldn't that match the lw_shared_ptr **pointer** rather than the labels value?

2024-12-26 11:44 UTC, bhalevy commented
Whatever we do, we cannot update the seastar submodule in scylla at the moment.
So I still vote for reverting ASAP and looking for an agreeable solution out of tree, and then resubmit the code while checking in advance that it doesn't break the user code.

2024-12-26 11:45 UTC, nyh commented
Just a small and **too late** bike-shedding comment:

The appropriate verb is **intern**, not "internalize".
Check out https://en.wikipedia.org/wiki/Interning_(computer_science). This term was first (as far as I know) introduced in Lisp, it's called intern in Java (https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#intern%28%29), in the X11 protocol (https://tronche.com/gui/x/xlib/window-information/XInternAtom.html), and probably many other systems I forgot.

2024-12-26 13:26 UTC, StephanDollberg commented
> Wouldn't that match the lw_shared_ptr pointer rather than the labels value?

No because metrics_family::at internally does the right thing (uses the holder type which has overloaded operator<).


> it doesn't break the user code

I don't think that's possible without changing the API level but that seems overkill for an internal change.

Whenever we update our seastar pointer in redpanda something breaks usually and we have to make some small changes. I don't think you want to hinder seastar changes just because it would require some changes in user code. That's why you pin the submodule pointer after all. And for such small changes the API level way is also lots of effort.

> The appropriate verb is intern, not "internalize".

Sure, don't think it's too late. Can just rename.

2024-12-26 15:04 UTC, bhalevy commented
> > The appropriate verb is intern, not "internalize".
> 
> Sure, don't think it's too late. Can just rename.

Well, this PR is already merged.

2024-12-26 19:21 UTC, travisdowns commented
The status of the `impl` namespaces with respect to API compatibility is unclear to me. It is clear that changes in the `internal` namespaces [are allowed without incrementing API version](https://github.com/scylladb/seastar/blob/master/doc/compatibility.md#internal-namespace) but the status of `impl` is unclear. My guess is that it would fall under the same rule as internal and it is simply an oversight that these few methods are in `seastar::impl` rather than `seastar::internal` or `seastar::internal::impl`. 

The `impl` namespace is only used in the metrics code and and one use is `when_all.h`.

> and then resubmit the code while checking in advance that it doesn't break the user code.

Assuming this ends up being judged to be in the internal interface, would this still be your suggestion?

2024-12-26 19:27 UTC, bhalevy commented
> The status of the `impl` namespaces with respect to API compatibility is unclear to me. It is clear that changes in the `internal` namespaces [are allowed without incrementing API version](https://github.com/scylladb/seastar/blob/master/doc/compatibility.md#internal-namespace) but the status of `impl` is unclear. My guess is that it would fall under the same rule as internal and it is simply an oversight that these few methods are in `seastar::impl` rather than `seastar::internal` or `seastar::internal::impl`.
> 
> The `impl` namespace is only used in the metrics code and and one use is `when_all.h`.
> 
> > and then resubmit the code while checking in advance that it doesn't break the user code.
> 
> Assuming this ends up being judged to be in the internal interface, would this still be your suggestion?

No, it wouldn't.