Add dq and dq_split
scylladb/seastar pull request #939
Opened 2021-09-03 13:02 UTC by pveentjer

Currently there exist sq, sq_split, mq and no_irq_restrictions. But on very
    powerful systems, these setting cause a bottleneck on IRQ processing. 2
    news options have been added: dq and dq_split. dq stands for double queue.
    
    Mode: dq
    
    This will create 2 IRQ CPUs:
    - CPU 0 of NUMA node 0
    - CPU 0 of NUMA node 1.
    
    Mode: dq_split
    
    This will create 4 IRQ CPUs:
    - CPU 0 and its sibling of NUMA node 0
    - CPU 0 and its sibling on NUMA node 1
    
    The one that is most valuable is the dq_split. On systems with many cores
    the 2 IRQ CPUs provided by sq_split are not sufficient to process the
    IRQs. So by usin dq_split, there is double the IRQ processing power.

2021-09-09 13:10 UTC, vladzcloudius requested changes
@pveentjer There is another configuration mode that you have missed - the most generic one: `--irq-cpu-mask`.

This mode allows you to choose any CPU set for IRQs handling.

I don't think it makes sense to add any additional "special" modes in addition to what we have right now.

It would actually make more sense to get rid of the existing ones in the future.

This patch in general makes little sense since you are adding a new modes while not adding a code that auto-detect when these new modes need to be used while this is the main idea of having those modes to begin with.

So, I'd recommend to do following changes:
 * Not add any new "special" modes and use `--irq-cpu-mask` infrastructure instead.
 * Add a new code that would auto-detect when 2 physical cores need to be used for IRQ handling.

2021-09-09 13:18 UTC, pveentjer commented
Hi Vlad. I did not miss the irq-cpu-mask setting. That is how I confirmed that on certain instance types the 2-irq CPU's were forming a bottleneck.

I even created a small tool in Scylla Stress Orchestrator to generate the bitmask because it is painful to configure these bitmaps by hand and that is the primary reason to introduce dq/dq_split.

2021-09-09 13:51 UTC, pveentjer commented
The explicit configuration of IRQ cpu's using bitmask is too much of a pain for most end users.

What we could do is to introduce a property e.g irq_cpu_count and get rid of the sq/sq_split etc options. 

If the irq_cpu_count property isn't set, we can do an educated guess (in the same was as we are currently guessing sq_split). 

And based on the irq_cpu_count and processor topology we can then determine how the IRQ cpu's should be spread over the physical cores.

This we we get rid of all the special modes and we have a single property that is easy to use. WDYT?

2021-09-09 18:35 UTC, vladzcloudius commented
> The explicit configuration of IRQ cpu's using bitmask is too much of a pain for most end users.
> 
> What we could do is to introduce a property e.g irq_cpu_count and get rid of the sq/sq_split etc options.
> 
> If the irq_cpu_count property isn't set, we can do an educated guess (in the same way as we are currently guessing sq/sq_split etc).
> 
> And based on the irq_cpu_count and processor topology we can then determine how the IRQ cpu's should be spread over the physical cores.
> 
> This way we get rid of all the special modes and we have a single property that is easy to use. So later if we need to add support for an system with 4 NUMA nodes, we don't need to add quadqueue and quadqueue_split. WDYT @vladzcloudius

Users are not supposed to explicitly define `mode` either - the script needs to correctly auto-detect it and then be able to use the result of this auto-detection. All this should happen automagically and users are not supposed to be involved in the process.

And because of that after `irq_cpu_mask` has been introduced we don't need `mode` anymore.
And this is not accidental - `irq_cpu_mask` was introduced exactly when we saw the issue with multi-NUMA setups and had the same dilemma you are trying to resolve here.
It was decided that expanding `mode` over and over again makes little sense and the most generic solution (`irq_cpu_mask`) has been proposed instead.

> What we could do is to introduce a property e.g irq_cpu_count and get rid of the sq/sq_split etc options.

We don't need to add anything to get rid of them as I explained above.

> If the irq_cpu_count property isn't set, we can do an educated guess (in the same way as we are currently guessing sq/sq_split etc).

It can be added but it would only create a complexity in the script that I think is not really needed.
Regular users are not supposed to play with the irq_cpu_mask.
And those that do need to play with it are supposed to be experienced enough to be able to run some trivial `hwloc` commands. We can even put a few examples in the `perftune.py --help`.

2021-09-10 04:33 UTC, pveentjer commented
Ok. I'll get rid of the new modes and work on auto configuration of the irq_cpu_mask.

2022-03-15 12:19 UTC, bhalevy commented
Closing this PR since its controversial.
Current direction is to go with https://github.com/scylladb/scylla/issues/9903 intsead.

2022-03-15 12:19 UTC, closed without merging